export { default as Footer } from "./Footer/Footer";
export { default as Hero } from "./Hero/Hero";
export { default as Inspiration } from "./Inspiration/Inspiration";
export { default as Navbar } from "./Navbar/Navbar";
export { default as NFT } from "./NFT/NFT";
export { default as Stay } from "./Stay/Stay";
export { default as Partners } from "./Partners/Partners";
export { default as StayCard } from "./StayCards/StayCard";
export { default as PlaceToStayCard } from "./PlaceToStayCard/PlaceToStayCard";
